---
# task/prerequisites file for update_motd
- name: "Install required roles"
  ansible.builtin.command:
    cmd: "ansible-galaxy install {{ item }}"
  loop: "{{ update_motd_prerequisites_roles }}"
  changed_when: false
  become: false
  delegate_to: localhost
  run_once: true
